"""Configuration for the Technical Indicators Dashboard."""

# Market settings
MARKET_OPEN_HOUR = 9
MARKET_OPEN_MINUTE = 15
MARKET_CLOSE_HOUR = 15
MARKET_CLOSE_MINUTE = 30
TIMEZONE = "Asia/Kolkata"

# Data settings
DATA_PERIOD = "1y"
DATA_INTERVAL = "1d"
CACHE_DIR = "cache"

# Indicator parameters
EMA_PERIOD = 5

SMI_K_PERIOD = 10
SMI_D_PERIOD = 3
SMI_SMOOTH = 3

RSI_PERIOD_SHORT = 5
RSI_PERIOD_LONG = 14
RSI_EMA_FAST = 5
RSI_EMA_SLOW = 55

DMI_PERIOD = 14
ADX_SMOOTHING = 14

ROC_SHORT = 5
ROC_LONG = 16
ROC_SMOOTH = 3

ATR_PERIOD = 14
ATR_RMA_PERIOD = 34

MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9

VOLUME_MA_PERIOD = 20

# Signal thresholds
SMI_OVERSOLD = -40
SMI_OVERBOUGHT = 40
ADX_TREND_THRESHOLD = 25
RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70
